displayName=Harrisun Mystic UI
author=Caleb
support=https://github.com/opaf-osrs/harrisun-mystic-ui
description=Minimap and orbs as a rectangular block above the inventory
tags=minimap,orbs,layout,hud,ui,resizable,mystic,harrisun
plugins=com.pluginideahub.mystichud.MysticHudPlugin
version=1.1
build=standard
