displayName=Mystic HUD
author=Caleb
support=https://github.com/opaf-osrs/mystic-hud
description=Minimap and orbs as a rectangular block above the inventory
tags=minimap,orbs,layout,hud,resizable,mystic
plugins=com.pluginideahub.mystichud.MysticHudPlugin
version=1.0
build=standard
